In [3]:
import pandas as pd

In [4]:
# Load datasets

# ======================

circuits=pd.read_csv('./dataset/circuits.csv',index_col='circuitId')

constructor_results=pd.read_csv('./dataset/constructor_results.csv',index_col='constructorResultsId')

constructor_standings=pd.read_csv('./dataset/constructor_standings.csv',index_col='constructorStandingsId')

constructors=pd.read_csv('./dataset/constructors.csv')

driver_standings=pd.read_csv('./dataset/driver_standings.csv',index_col='driverStandingsId')

drivers=pd.read_csv('./dataset/drivers.csv',index_col='driverId')

lap_times=pd.read_csv('./dataset/lap_times.csv',index_col='raceId')

pit_stops=pd.read_csv('./dataset/pit_stops.csv',index_col='raceId')

qualifying=pd.read_csv('./dataset/qualifying.csv',index_col='qualifyId')

races=pd.read_csv('./dataset/races.csv',index_col='raceId')

results=pd.read_csv('./dataset/results.csv',index_col='resultId')

seasons=pd.read_csv('./dataset/seasons.csv',index_col='year')

sprint_results=pd.read_csv('./dataset/sprint_results.csv',index_col='resultId')

status=pd.read_csv('./dataset/status.csv',index_col='statusId')

#análises
1 - Quem são os pilotos com mais vitórias e pontos?
2 - Que equipas dominaram a Fórmula 1?
3 - Começar em primeiro aumenta as hipóteses de ganhar?
4 - Em que circuitos há mais abandonos?
5 - Qual o top10 das nacionalidades dos pilotos com mais vitórias?
6 - Quem tem melhor consistência ao longo da carreira?

In [5]:
df1 = results.merge(
    drivers,
    left_on='driverId',
    right_index=True,
    how='left'
)

df1 = df1.rename(columns={
    'number_x' : 'number',
})

df1=df1.drop(columns=['number_y'])
df1

df1

,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,...,fastestLapTime,fastestLapSpeed,statusId,driverRef,code,forename,surname,dob,nationality,url
resultId,,,,,,,,,,,,,,,,,,,,,
1,18,1,1,22,1,1,1,1,10.0,58,...,1:27.452,218.300,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
2,18,2,2,3,5,2,2,2,8.0,58,...,1:27.739,217.586,1,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
3,18,3,3,7,7,3,3,3,6.0,58,...,1:28.090,216.719,1,rosberg,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
4,18,4,4,5,11,4,4,4,5.0,58,...,1:28.603,215.464,1,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
5,18,5,1,23,3,5,5,5,4.0,58,...,1:27.418,218.385,1,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26520,1132,839,214,31,18,16,16,16,0.0,50,...,1:30.875,233.371,12,ocon,OCO,Esteban,Ocon,1996-09-17,French,http://en.wikipedia.org/wiki/Esteban_Ocon
26521,1132,815,9,11,0,17,17,17,0.0,50,...,1:29.707,236.409,12,perez,PER,Sergio,Pérez,1990-01-26,Mexican,http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez
26522,1132,855,15,24,14,18,18,18,0.0,50,...,1:31.014,233.014,12,zhou,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Zhou_Guanyu
26523,1132,847,131,63,1,\N,R,19,0.0,33,...,1:31.298,232.289,34,russell,RUS,George,Russell,1998-02-15,British,http://en.wikipedia.org/wiki/George_Russell_(r...
26524,1132,842,214,10,19,\N,W,20,0.0,0,...,\N,\N,6,gasly,GAS,Pierre,Gasly,1996-02-07,French,http://en.wikipedia.org/wiki/Pierre_Gasly

In [6]:
#Top 10 pilotos com mais pontos

points = df1.groupby('driverRef')['points'].sum().sort_values(ascending=False)
print(points.head(10))

driverRef
hamilton              4713.5
vettel                3098.0
max_verstappen        2744.5
alonso                2304.0
raikkonen             1873.0
bottas                1788.0
rosberg               1594.5
michael_schumacher    1566.0
perez                 1552.0
ricciardo             1319.0
Name: points, dtype: float64

In [7]:
#top 10 pilotos com mais vitórias

wins = df1[df1['positionOrder'] == 1]['driverRef'].value_counts()
wins.head(10)

driverRef
hamilton              104
michael_schumacher     91
max_verstappen         61
vettel                 53
prost                  51
senna                  41
alonso                 32
mansell                31
stewart                27
lauda                  25
Name: count, dtype: int64

In [8]:
#2 - Que equipas dominaram a Fórmula 1? por pontos

In [9]:
df2 = results.merge(
    constructors,
    left_on='constructorId',
    right_index=True,
    how='left'
)

df2=df2.drop(columns=['constructorId_y','constructorId_x'])
df2

,constructorId,raceId,driverId,number,grid,position,positionText,positionOrder,points,laps,...,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,constructorRef,name,nationality,url
resultId,,,,,,,,,,,,,,,,,,,,,
1,1,18,1,22,1,1,1,1,10.0,58,...,5690616,39,2,1:27.452,218.300,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,2,18,2,3,5,2,2,2,8.0,58,...,5696094,41,3,1:27.739,217.586,1,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,3,18,3,7,7,3,3,3,6.0,58,...,5698779,41,5,1:28.090,216.719,1,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,4,18,4,5,11,4,4,4,5.0,58,...,5707797,58,7,1:28.603,215.464,1,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,1,18,5,23,3,5,5,5,4.0,58,...,5708630,43,1,1:27.418,218.385,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26520,214,1132,839,31,18,16,16,16,0.0,50,...,\N,46,16,1:30.875,233.371,12,NaN,NaN,NaN,NaN
26521,9,1132,815,11,0,17,17,17,0.0,50,...,\N,50,6,1:29.707,236.409,12,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
26522,15,1132,855,24,14,18,18,18,0.0,50,...,\N,43,17,1:31.014,233.014,12,bar,BAR,British,http://en.wikipedia.org/wiki/British_American_...
26523,131,1132,847,63,1,\N,R,19,0.0,33,...,\N,3,19,1:31.298,232.289,34,hwm,HWM,British,http://en.wikipedia.org/wiki/Hersham_and_Walto...
26524,214,1132,842,10,19,\N,W,20,0.0,0,...,\N,\N,0,\N,\N,6,NaN,NaN,NaN,NaN

In [10]:
points_constructor = df2.groupby('constructorRef')['points'].sum().sort_values(ascending=False)
print(points_constructor.head(10))

constructorRef
toyota         10772.27
hwm             7502.64
force_india     7472.00
bmw_sauber      6687.50
renault         3628.00
toro_rosso      1777.00
honda           1098.00
larrousse        995.00
brawn            861.50
lola             711.00
Name: points, dtype: float64

In [11]:
#2 - Que equipas dominaram a Fórmula 1? por mais vitórias

In [12]:
wins_constructors = df2[df2['positionOrder'] == 1]['constructorRef'].value_counts()
wins_constructors.head(10)

constructorRef
toyota         246
bmw_sauber     180
hwm            127
force_india    120
renault        114
larrousse       45
toro_rosso      35
brawn           27
lola            23
dallara         23
Name: count, dtype: int64

In [13]:
#3 - Começar em primeiro aumenta as hipóteses de ganhar?

In [14]:
df3 = qualifying.merge(
    results,
    on=['raceId','driverId'],
    how='left'
)

df3 = df3.rename(columns={
    'position_x': 'position',
    'number_x': 'number',
    'constructorId_x': 'constructor',
})

df3=df3.drop(columns=['constructorId_y','number_y','position_y'])

df3

,raceId,driverId,constructor,number,position,q1,q2,q3,grid,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,18,1,1,22,1,1:26.572,1:25.187,1:26.714,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,18,9,2,4,2,1:26.103,1:25.315,1:26.869,2,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
2,18,5,1,23,3,1:25.664,1:25.452,1:27.079,3,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
3,18,13,6,2,4,1:25.994,1:25.691,1:27.178,4,R,13,0.0,29,\N,\N,23,6,1:28.175,216.510,5
4,18,2,2,3,5,1:25.960,1:25.518,1:27.236,5,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10249,1132,822,15,77,16,1:32.431,\N,\N,16,15,15,0.0,51,\N,\N,44,18,1:31.277,232.343,11
10250,1132,825,210,20,17,1:32.905,\N,\N,17,12,12,0.0,52,+1:30.153,5037212,42,13,1:30.093,235.396,1
10251,1132,839,214,31,18,1:34.557,\N,\N,18,16,16,0.0,50,\N,\N,46,16,1:30.875,233.371,12
10252,1132,815,9,11,19,1:38.348,\N,\N,0,17,17,0.0,50,\N,\N,50,6,1:29.707,236.409,12
10253,1132,842,214,10,20,1:39.804,\N,\N,19,W,20,0.0,0,\N,\N,\N,0,\N,\N,6

In [15]:
pole_wins = df3[df3['position'] == 1]
wins = pole_wins[pole_wins['positionOrder'] == 1]
print(len(wins))
prob = len(wins) / len(pole_wins)
print(prob)

242
0.5020746887966805

#Existe a probabilidade de 50% de ao começar na primeira posição resultar na vitória

In [ ]:
#4 - Em que circuitos há mais abandonos? E a que condutores se refere (Top10)

In [64]:
df4 = races.merge(
    circuits,
    left_on='circuitId',
    right_index=True,
    how='left'
)

df4 = df4.rename(columns={
    'name_x': 'name',
    'url_x': 'url',
})

df4=df4.drop(columns=['url_y','name_y'])
df4

df5 = df4.merge(
    results,
    left_on='raceId',
    right_index=True,
    how='left'
)

df5 = df5.rename(columns={
    'time_x': 'time',
})

df5=df5.drop(columns=['time_y'])
df5

df6 = df5.merge(
    drivers,
    left_on='driverId',
    right_index=True,
    how='left'
)

df6 = df6.rename(columns={
    'url_x': 'url',
    'number_x':'number'
})

df6=df6.drop(columns=['url_y','number_y'])
df6

,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,...,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,code,forename,surname,dob,nationality
raceId,,,,,,,,,,,,,,,,,,,,,
1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,...,2,1:27.452,218.300,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British
2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,...,3,1:27.739,217.586,1,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German
3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,...,5,1:28.090,216.719,1,rosberg,ROS,Nico,Rosberg,1985-06-27,German
4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,...,7,1:28.603,215.464,1,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish
5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,...,1,1:27.418,218.385,1,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,...,3,1:26.233,221.386,1,barrichello,BAR,Rubens,Barrichello,1972-05-23,Brazilian
1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,...,1,1:25.683,222.807,1,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish
1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,...,11,1:26.690,220.219,1,coulthard,COU,David,Coulthard,1971-03-27,British
1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,...,8,1:26.493,220.720,1,webber,WEB,Mark,Webber,1976-08-27,Australian
1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,...,7,1:26.393,220.976,1,montoya,MON,Juan,Pablo Montoya,1975-09-20,Colombian

In [74]:
df6['time'].convert_dtypes(str)
abandonos = df6[df6['time'] == '\\N']

print(f'{abandonos.shape[0]} pilotos abandonaram a corrida.\n')

abandonos_circuito = abandonos.groupby('name').size().sort_values(ascending=False)
 
print("Os circuitos com mais abandonos foram:\n")
print(abandonos_circuito.head(10))

731 pilotos abandonaram a corrida.

Os circuitos com mais abandonos foram:

name
British Grand Prix      55
Italian Grand Prix      55
French Grand Prix       54
German Grand Prix       52
Monaco Grand Prix       51
Belgian Grand Prix      50
Canadian Grand Prix     36
Spanish Grand Prix      34
Brazilian Grand Prix    32
Dutch Grand Prix        30
dtype: int64

In [75]:
abandonos_condutores = abandonos.groupby('driverRef').size().sort_values(ascending=False)
 
print("\nOs pilotos com mais abandonos foram:\n")
print(abandonos_condutores.head(10))

Os pilotos com mais abandonos foram:

driverRef
alonso         35
barrichello    35
heidfeld       35
trulli         35
fisichella     35
raikkonen      35
rosberg        35
webber         34
massa          34
button         34
dtype: int64

In [88]:
#5 - Qual o top10 das nacionalidades dos pilotos com mais vitórias?

In [92]:
vitorias = df1[df1['position'] == '1']
 
nacionalidades = vitorias.groupby('nationality').size().sort_values(ascending=False)
 
print("Nacionalidades com mais vitórias na Fórmula 1:\n")
print(nacionalidades.head(10))

Nacionalidades com mais vitórias na Fórmula 1:

nationality
British       312
German        179
Brazilian     101
French         81
Dutch          61
Finnish        57
Australian     43
Italian        43
Austrian       41
Argentine      38
dtype: int64

In [100]:
#6 - Quem tem melhor consistência ao longo da carreira? (mediana dos pontos)

In [99]:
mediana_pontos = df1.groupby('driverRef')['points'].median().sort_values(ascending=False)
print("Pilotos mais consistentes (mediana dos pontos):\n")
print(mediana_pontos.head(10))

Pilotos mais consistentes (mediana dos pontos):

driverRef
max_verstappen        15.0
hamilton              13.0
vettel                10.0
leclerc                8.0
george_amick           6.0
norris                 6.0
michael_schumacher     6.0
bearman                6.0
bottas                 6.0
fangio                 6.0
Name: points, dtype: float64

In [ ]:
#não fizemos a análise pela mediana dos pontos, pois há casos onde o piloto recebe pontos e não terminou a prova