In [1]:
import pandas as pd

In [24]:
# Load datasets

# ======================

circuits=pd.read_csv('./dataset/circuits.csv',index_col='circuitId')

constructor_results=pd.read_csv('./dataset/constructor_results.csv',index_col='constructorResultsId')

constructor_standings=pd.read_csv('./dataset/constructor_standings.csv',index_col='constructorStandingsId')

constructors=pd.read_csv('./dataset/constructors.csv')

driver_standings=pd.read_csv('./dataset/driver_standings.csv',index_col='driverStandingsId')

drivers=pd.read_csv('./dataset/drivers.csv',index_col='driverId')

lap_times=pd.read_csv('./dataset/lap_times.csv',index_col='raceId')

pit_stops=pd.read_csv('./dataset/pit_stops.csv',index_col='raceId')

qualifying=pd.read_csv('./dataset/qualifying.csv',index_col='qualifyId')

races=pd.read_csv('./dataset/races.csv',index_col='raceId')

results=pd.read_csv('./dataset/results.csv',index_col='resultId')

seasons=pd.read_csv('./dataset/seasons.csv',index_col='year')

sprint_results=pd.read_csv('./dataset/sprint_results.csv',index_col='resultId')

status=pd.read_csv('./dataset/status.csv',index_col='statusId')

#análises
1 - Quem são os pilotos com mais vitórias e pontos?
2 - Que equipas dominaram a Fórmula 1?
3 - Começar em primeiro aumenta as hipóteses de ganhar?
4 - Em que circuitos há mais abandonos?
5 - Quantos pilotos diferentes ganham corridas por ano?
6 - Quem tem melhor consistência ao longo da carreira?

In [32]:
df1 = results.merge(
    drivers,
    left_on='driverId',
    right_index=True,
    how='left'
)

df1 = df1.rename(columns={
    'number_x' : 'number',
})

df1=df1.drop(columns=['number_y'])
df1

df1

,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,...,fastestLapTime,fastestLapSpeed,statusId,driverRef,code,forename,surname,dob,nationality,url
resultId,,,,,,,,,,,,,,,,,,,,,
1,18,1,1,22,1,1,1,1,10.0,58,...,1:27.452,218.300,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
2,18,2,2,3,5,2,2,2,8.0,58,...,1:27.739,217.586,1,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
3,18,3,3,7,7,3,3,3,6.0,58,...,1:28.090,216.719,1,rosberg,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
4,18,4,4,5,11,4,4,4,5.0,58,...,1:28.603,215.464,1,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
5,18,5,1,23,3,5,5,5,4.0,58,...,1:27.418,218.385,1,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26520,1132,839,214,31,18,16,16,16,0.0,50,...,1:30.875,233.371,12,ocon,OCO,Esteban,Ocon,1996-09-17,French,http://en.wikipedia.org/wiki/Esteban_Ocon
26521,1132,815,9,11,0,17,17,17,0.0,50,...,1:29.707,236.409,12,perez,PER,Sergio,Pérez,1990-01-26,Mexican,http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez
26522,1132,855,15,24,14,18,18,18,0.0,50,...,1:31.014,233.014,12,zhou,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Zhou_Guanyu
26523,1132,847,131,63,1,\N,R,19,0.0,33,...,1:31.298,232.289,34,russell,RUS,George,Russell,1998-02-15,British,http://en.wikipedia.org/wiki/George_Russell_(r...
26524,1132,842,214,10,19,\N,W,20,0.0,0,...,\N,\N,6,gasly,GAS,Pierre,Gasly,1996-02-07,French,http://en.wikipedia.org/wiki/Pierre_Gasly

In [37]:
#Top 10 pilotos com mais pontos

points = df1.groupby('driverRef')['points'].sum().sort_values(ascending=False)
print(points.head(10))

driverRef
hamilton              4713.5
vettel                3098.0
max_verstappen        2744.5
alonso                2304.0
raikkonen             1873.0
bottas                1788.0
rosberg               1594.5
michael_schumacher    1566.0
perez                 1552.0
ricciardo             1319.0
Name: points, dtype: float64

In [38]:
#top 10 pilotos com mais vitórias

wins = df1[df1['positionOrder'] == 1]['driverRef'].value_counts()
wins.head(10)

driverRef
hamilton              104
michael_schumacher     91
max_verstappen         61
vettel                 53
prost                  51
senna                  41
alonso                 32
mansell                31
stewart                27
lauda                  25
Name: count, dtype: int64

In [ ]:
#2 - Que equipas dominaram a Fórmula 1? por pontos

In [43]:
df2 = results.merge(
    constructors,
    left_on='constructorId',
    right_index=True,
    how='left'
)

df2=df2.drop(columns=['constructorId_y','constructorId_x'])
df2

,constructorId,raceId,driverId,number,grid,position,positionText,positionOrder,points,laps,...,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,constructorRef,name,nationality,url
resultId,,,,,,,,,,,,,,,,,,,,,
1,1,18,1,22,1,1,1,1,10.0,58,...,5690616,39,2,1:27.452,218.300,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,2,18,2,3,5,2,2,2,8.0,58,...,5696094,41,3,1:27.739,217.586,1,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,3,18,3,7,7,3,3,3,6.0,58,...,5698779,41,5,1:28.090,216.719,1,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,4,18,4,5,11,4,4,4,5.0,58,...,5707797,58,7,1:28.603,215.464,1,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,1,18,5,23,3,5,5,5,4.0,58,...,5708630,43,1,1:27.418,218.385,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26520,214,1132,839,31,18,16,16,16,0.0,50,...,\N,46,16,1:30.875,233.371,12,NaN,NaN,NaN,NaN
26521,9,1132,815,11,0,17,17,17,0.0,50,...,\N,50,6,1:29.707,236.409,12,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
26522,15,1132,855,24,14,18,18,18,0.0,50,...,\N,43,17,1:31.014,233.014,12,bar,BAR,British,http://en.wikipedia.org/wiki/British_American_...
26523,131,1132,847,63,1,\N,R,19,0.0,33,...,\N,3,19,1:31.298,232.289,34,hwm,HWM,British,http://en.wikipedia.org/wiki/Hersham_and_Walto...
26524,214,1132,842,10,19,\N,W,20,0.0,0,...,\N,\N,0,\N,\N,6,NaN,NaN,NaN,NaN

In [45]:
points_constructor = df2.groupby('constructorRef')['points'].sum().sort_values(ascending=False)
print(points_constructor.head(10))

constructorRef
toyota         10772.27
hwm             7502.64
force_india     7472.00
bmw_sauber      6687.50
renault         3628.00
toro_rosso      1777.00
honda           1098.00
larrousse        995.00
brawn            861.50
lola             711.00
Name: points, dtype: float64

In [ ]:
#2 - Que equipas dominaram a Fórmula 1? por mais vitórias

In [48]:
wins_constructors = df2[df2['positionOrder'] == 1]['constructorRef'].value_counts()
wins_constructors.head(10)

constructorRef
toyota         246
bmw_sauber     180
hwm            127
force_india    120
renault        114
larrousse       45
toro_rosso      35
brawn           27
lola            23
dallara         23
Name: count, dtype: int64

In [ ]:
#3 - Começar em primeiro aumenta as hipóteses de ganhar?

In [57]:
df3 = qualifying.merge(
    results,
    on=['raceId','driverId'],
    how='left'
)

df3 = df3.rename(columns={
    'position_x': 'position',
    'number_x': 'number',
    'constructorId_x': 'constructor',
})

df3=df3.drop(columns=['constructorId_y','number_y','position_y'])

df3

,raceId,driverId,constructor,number,position,q1,q2,q3,grid,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,18,1,1,22,1,1:26.572,1:25.187,1:26.714,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,18,9,2,4,2,1:26.103,1:25.315,1:26.869,2,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
2,18,5,1,23,3,1:25.664,1:25.452,1:27.079,3,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
3,18,13,6,2,4,1:25.994,1:25.691,1:27.178,4,R,13,0.0,29,\N,\N,23,6,1:28.175,216.510,5
4,18,2,2,3,5,1:25.960,1:25.518,1:27.236,5,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10249,1132,822,15,77,16,1:32.431,\N,\N,16,15,15,0.0,51,\N,\N,44,18,1:31.277,232.343,11
10250,1132,825,210,20,17,1:32.905,\N,\N,17,12,12,0.0,52,+1:30.153,5037212,42,13,1:30.093,235.396,1
10251,1132,839,214,31,18,1:34.557,\N,\N,18,16,16,0.0,50,\N,\N,46,16,1:30.875,233.371,12
10252,1132,815,9,11,19,1:38.348,\N,\N,0,17,17,0.0,50,\N,\N,50,6,1:29.707,236.409,12
10253,1132,842,214,10,20,1:39.804,\N,\N,19,W,20,0.0,0,\N,\N,\N,0,\N,\N,6

In [58]:
pole_wins = df3[df3['position'] == 1]
wins = pole_wins[pole_wins['positionOrder'] == 1]
print(len(wins))
prob = len(wins) / len(pole_wins)
print(prob)

242
0.5020746887966805

#Existe a probabilidade de 50% de ao começar na primeira posição resultar na vitória